networks:
  cloudflared:
    external: true

services:
  headless-oxider:
    networks:
      - cloudflared
    extra_hosts:
      - "host.docker.internal:host-gateway"

  headless-oxider-headful:
    networks:
      - cloudflared
    extra_hosts:
      - "host.docker.internal:host-gateway"
